### PR TITLE
Improve molecule tests

### PR DESCRIPTION
**Pull request by nre-ableton**
This PR:

- Adds a `requirements-dev.txt` file which developers can use to install all Python packages needed to run the molecule tests
- Adds a corresponding `requirements-dev.in` file (which can generate the `requirements-dev.txt` using [`pip-tools`](https://pypi.org/project/pip-tools/))
- Adds a dependabot YAML configuration file so that `requirements-dev.txt` is kept up-to-date by [dependabot](https://dependabot.com/)
- Adds some very basic testinfra sanity tests to ensure that the clang versions are installed
- Expands the default molecule scenario to test all currently working clang versions (there are other issues with clang 5.0, 6.0, 7, and 9, and discussed in https://github.com/Provizanta/ansible-role-clang/issues/2).

Apologies if this is too many commits for a single PR; I'd be happy to break it up if that makes things easier to review.

### CODE REVIEW

**Comment by nre-ableton** [comment]
Also, I cannot get the idempotency checks of molecule to work because installing a lower version of clang will remove newer versions, like so:

```
TASK [ansible-role-clang : establish clang tools] ******************************
The following packages were automatically installed and are no longer required:
  liblldb-10 liblldb-11 liblldb-7 libpython2.7 python-six
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libc++1-12 libc++abi1-12 libomp5-12
Suggested packages:
  clang libomp-12-doc
The following packages will be REMOVED:
  libc++-11-dev libc++1-11 libc++abi-11-dev libc++abi1-11 libllvm-11-ocaml-dev
  libomp-11-dev libomp5-11 python3-clang-11
The following NEW packages will be installed:
  libc++-12-dev libc++1-12 libc++abi-12-dev libc++abi1-12 libllvm-12-ocaml-dev
  libomp-12-dev libomp5-12 python3-clang-12
0 upgraded, 8 newly installed, 8 to remove and 5 not upgraded.
```

I'm not sure how to solve this, but I have a few ideas. In the meantime, this is at least a good start to improving the role's molecule tests.

**Comment by nre-ableton** [comment]
I've converted this PR to a draft until I sort out the CI failures.

**Comment by Teebor-Choka** [comment]
@nre-ableton, did you close this draft, because you don't intend to create the final PR?

**Comment by Teebor-Choka** [comment]
Also, what is your motivation to have multiple clang compilers on a single host. I'd expect a dedicated builder with a specific clang version for the project. You could then swap the builder.

**Comment by nre-ableton** [comment]
I closed the draft because I couldn't get the unit tests working, and we decided to go another direction with our clang Ansible roles.

As for why we install multiple clang versions, our CI setup offers some generic linux nodes that are expected to have multiple compiler versions and other language support.

**Comment by Teebor-Choka** [comment]
I'd still advice to use specialized containers for that. Good luck on your clang journeys! :beers:

**Pull request closed without merging**
